from .base import DistilLoss
from .fkl import ForwardKL
from .rkl import ReverseKL
from .tvd import TVD
from .js import JS
from .adaptive_kl import AdaptiveKL
from .skew_fkl import SkewForwardKL
from .skew_rkl import SkewReverseKL
from .ctkd import CTKD
from .dkd import DKD
from .taid import TAID
